spring:
  # 修复数据源配置层级
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: "1234"
  web:
    upload-path: D:\Project\Ruanjiangc\dust
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
